ROOT: /home/siluo/public/SiyuanLuo/projects/benchmark/outputs/Cell_line_mixing # Edit it
r_env : base
py_env : snapatac2
reticulate_py: /home/siluo/softwares/mambaforge-pypy3/envs/r-reticulate/bin/python

# MACS2_PATH: /home/siluo/Software/mambaforge/envs/macs2/bin/macs2
MACS2_PATH: /home/siluo/softwares/mambaforge-pypy3/envs/macs2/bin/macs2

FEATURE_SELECTION:
  ndim:
   - 15
  #  - 30
  #  - 50
  #  - 100
  cutoff: 0.75

GRAPH_CONSTRUCTION:
  use_umap: false
  k_umap: 20
  

METHODS:

# R methods
 Signac:
    # distance:
    #   - Euclidean
   R: true
   feature_type:
     - all_cell_peaks
     - by_cluster_peaks
   peak_filtering: true


 ArchR:
  # distance:
  #   - Euclidean
   R: true
   feature_type:
     - tiles
     - peaks
   peak_filtering: false # ArchR already filters peak by only using reproducible peaks
   tile_size:
     - 500

 SnapATAC1: # should have snaptools installed in the r_env
 # distance:
 #   - Euclidean
   R: true
   feature_type:
     - default
   peak_filtering: false   # TODO: add this as the default
   tile_size:
      - 5000


 aggregation:
   R: true
   feature_type:
    - default
   peak_filtering: false   # TODO: add this as the default
   n_meta_features: 1000
   n_cells: 2000
   norm_method: tfidf
   reduce: pca
   feature_method: signac_cluster
   tile_size:
     - 500

# Python methods
 SnapATAC2:
   R: false
   feature_type:
    - default
   distance:
    - jaccard
    - cosine
   peak_filtering: false   # TODO: add this as the default
   tile_size:
     - 500

DATA_SCENARIOS:
  Cell_line_mixing: # Edit it
    organism: human # Edit it
    assay: ATAC
    file: /home/siluo/public/SiyuanLuo/projects/benchmark/cleaned_data/Cell_line_mixing/GSE162690_CellLine.fragments.filtered.sorted.sorted.tsv.gz # Edit it
    genome: hg19 # Edit it
    blacklist: blacklist_hg19 # Edit it

    seed:
     - 0
     - 2
     - 5
     - 42
     - 123

    resolution:  # Edit it
     - 0.05
     - 0.1
     - 0.15
     - 0.2
    #  - 0.25
     - 0.3
    #  - 0.35
    #  - 0.4
    #  - 0.45
    #  - 0.5
    #  - 0.55
    #  - 0.6
    #  - 0.65
    #  - 0.7
    #  - 0.75
    #  - 0.8
    #  - 0.85
    #  - 0.9
    #  - 0.95
    #  - 1
    #  - 1.1
    #  - 1.2
    #  - 1.3
    #  - 1.4
    #  - 1.5
    #  - 1.6
     
    min_width: 20
    max_width: 10000
    iter_resolution: 0.05,0.1,0.2 # Edit it
    label_table_file: /home/siluo/public/SiyuanLuo/projects/benchmark/cleaned_data/Cell_line_mixing/Cell_id_demuxlet_prediction.txt # Edit it
    barcode_col: barcode # Edit it
    label_col: prediction # Edit it
  

