ROOT: /home/siluo/public/SiyuanLuo/projects/benchmark/outputs/Chen_2019
r_env : base
# mamba create -n sc-chrom-R4 -c conda-forge -c bioconda r-base=4* r-essentials r-rlang r-signac r-seurat=4* xgboost bioconductor-GenomeInfoDb bioconductor-EnsDb.Hsapiens.v75 bioconductor-EnsDb.Hsapiens.v86 bioconductor-EnsDb.Mmusculus.v79 r-optparse bioconductor-biovizbase leidenalg pandas
# undo previous changes on .Renviron
py_env : snapatac2
reticulate_py: NA #/home/siluo/softwares/mambaforge-pypy3/envs/r-reticulate/bin/python

MACS2_PATH: /home/siluo/Software/mambaforge/envs/macs2/bin/macs2
# MACS2_PATH: /home/siluo/softwares/mambaforge-pypy3/envs/macs2/bin/macs2

FEATURE_SELECTION:
  ndim:
   - 15
  #  - 30
  #  - 50
  #  - 100
  cutoff: 0.75

SCALING: false

GRAPH_CONSTRUCTION:
  use_umap: false
  k_umap: 20
  

METHODS:

# R methods
 Signac:
    # distance:
    #   - Euclidean
   R: true
   feature_type:
     - all_cell_peaks
     - by_cluster_peaks
   peak_filtering: true


 ArchR:
  # distance:
  #   - Euclidean
   R: true
   feature_type:
     - tiles
     - peaks
   peak_filtering: false # ArchR already filters peak by only using reproducible peaks
   tile_size:
     - 500

 SnapATAC1: # should have snaptools installed in the r_env
 # distance:
 #   - Euclidean
   R: true
   feature_type:
     - default
   peak_filtering: false   # TODO: add this as the default
   tile_size:
      - 5000


 aggregation:
   R: true
   feature_type:
    - default
   peak_filtering: false   # TODO: add this as the default
   n_meta_features: 1000
   n_cells: 2000
   norm_method: tfidf
   reduce: pca
   feature_method: signac_cluster
   tile_size:
     - 500

#  aggregation2:
#    R: true
#    feature_type:
#     - default
#    peak_filtering: false   # TODO: add this as the default
#    norm_method: tfidf
#    resolution: 5
#    reduce: pca
#    feature_method: signac_cluster
#    tile_size:
#      - 500


# Python methods
 SnapATAC2:
   R: false
   feature_type:
    - default
   distance:
    - jaccard
    - cosine
   peak_filtering: false   # TODO: add this as the default
   tile_size:
     - 500

DATA_SCENARIOS:
  Chen_2019:
    organism: mouse
    assay: ATAC
    file: /home/siluo/public/SiyuanLuo/projects/benchmark/cleaned_data/Chen_2019/Chen_2019_filtered_fragments_sorted.bed.gz
    # /home/siluo/projects/sc_chromatin_benchmark/cleaned_data/Chen_2019_filtered_fragments_sorted.bed.gz
    genome: mm10
    blacklist: blacklist_mm10

    seed:
     - 0
     - 2
     - 5
     - 42
     - 123
    #  - 197

    resolution: 
    #  - 0.01
    #  - 0.02
    #  - 0.03
    #  - 0.04
    #  - 0.05
    #  - 0.05625
    #  - 0.0625 # before: only for the agg method
    #  - 0.075

    #  - 0.1
     - 0.125
    #  - 0.15
    #  - 0.175
     - 0.2
    #  - 0.225
    #  - 0.25
     - 0.3
     - 0.35
     - 0.4

     - 0.45
     - 0.5
     - 0.55
    #  - 0.6
    #  - 0.65
    #  - 0.7
    #  - 0.75
    #  - 0.8
    #  - 0.85
    #  - 0.9

    min_width: 20
    max_width: 10000
    iter_resolution: 0.1,0.2,0.3
    label_table_file: /home/siluo/public/SiyuanLuo/projects/benchmark/cleaned_data/Chen_2019/Chen_2019_RNA_annotation.txt
    barcode_col: barcode
    label_col: final_label
  
  # candidate2:
  #   resolution:
  #    - 0.2
