ROOT: outputs
r_env : base
# mamba create -n sc-chrom-R4 -c conda-forge -c bioconda r-base=4* r-essentials r-rlang r-signac r-seurat=4* xgboost bioconductor-GenomeInfoDb bioconductor-EnsDb.Hsapiens.v75 bioconductor-EnsDb.Hsapiens.v86 bioconductor-EnsDb.Mmusculus.v79 r-optparse bioconductor-biovizbase leidenalg pandas
# undo previous changes on .Renviron
py_env : snakemake


MACS2_PATH: /home/siluo/Software/mambaforge/envs/macs2/bin/macs2
#  /home/siluo/softwares/mambaforge-pypy3/envs/macs2/bin/macs2

FEATURE_SELECTION:
  ndim: 
  # - 30
  - 50
  # - 100
  cutoff: 0.75

METHODS:
# python methods
  # snapATAC2:
  #   R: true


# R methods
  # snapATAC:
  #   R: true
  # r_env: snapATAC

  Signac:
    # distance:
    #   - Euclidean
    R: true
    feature_type:
      # - all_cell_peaks
      - by_cluster_peaks
    peak_calling: true


  # ArchR:
  #   R: true

  # aggregation:
  #   R: true


DATA_SCENARIOS:
  test_data_large_r4:
    batch_key: batch
    label_key: celltype
    organism: mouse
    assay: expression
    file: cleaned_data/test_data_large/GSE162690_CellLine_LowLoading.fragments.tsv.gz
    genome: hg19
    blacklist: blacklist_hg19
    resolution: 
     - 0.1
    min_width: 20
    max_width: 10000